parameters:
    candm_simpleitem.form.type.simpleitem.class: ClickAndMortar\SimpleItemBundle\Form\SimpleItemType

services:
    candm_simpleitem.form.type.simpleitem:
        class: '%candm_simpleitem.form.type.simpleitem.class%'
        tags:
            - { name: form.type, alias: candm_simpleitem_form_type_simpleitem }