ClickAndMortar\SimpleItemBundle\Entity\SimpleItem:
    properties:
        label:
            - NotBlank: ~

ClickAndMortar\SimpleItemBundle\Entity\SimpleList:
    properties:
        label:
            - NotBlank: ~
        value:
            - NotBlank: ~