operations:
    candm_simpleitem_add_simpleitem:
        label: clickandmortar.simpleitem.simplelist.custom.actions.add_simpleitem
        applications: [default]
        routes: [candm_simpleitem_simplelist_view]

        button_options:
            icon: fa-plus

        frontend_options:
            template: ClickAndMortarSimpleItemBundle:Action:addSimpleItem.html.twig
            options:
                allowMaximize: true
                allowMinimize: true
                dblclick: maximize
                maximizedHeightDecreaseBy: minimize-bar
                width: 650

        attributes:
            simpleitem:
                label: clickandmortar.simpleitem.entity_label
                type: entity
                options:
                    class: ClickAndMortar\SimpleItemBundle\Entity\SimpleItem

        form_options:
                attribute_fields:
                    simpleitem:
                        form_type: candm_simpleitem_form_type_simpleitem
                        options:
                            required: true
                attribute_default_values:
                    simpleitem: $.simpleitem

        form_init:
            - '@create_object':
                class: ClickAndMortar\SimpleItemBundle\Entity\SimpleItem
                attribute: $.simpleitem
            - '@assign_value': [$.simpleItem.list, $.data]

        actions:
            - '@create_entity':
                class: ClickAndMortar\SimpleItemBundle\Entity\SimpleItem
                attribute: $.simpleitem
                data:
                    label: $.simpleitem.label
                    value: $.simpleitem.value
                    image: $.simpleitem.image
                    list: $.data
                flush: true
            - '@flash_message':
                message: clickandmortar.simpleitem.simplelist.custom.actions.add_simpleitem_save_sucess
                type: 'success'